export const Questions=[
    {
        prompt:'Who was JS Parnell',
        optionA:'The first High King of Ireland',
        optionB:'Yoko Onos Lover',
        optionC:'Irelands first president',
        optionD:'The leader of the Home Rule League',
        url:'https://headstuffuploads.s3.amazonaws.com/2018/09/11193219/parnell.jpg',
        answer:'D', 
    },
    {
        prompt:'Who was Brian Boru',
        optionA:'The last High King of Ireland',
        optionB:'The first High King of Ireland',
        optionC:'Irelands first president',
        optionD:'Michael Collins lover',
        url:'https://i.pinimg.com/originals/5f/4d/3f/5f4d3ff6383c3cde9d9b9c400833197f.jpg',
        answer:'B', 
    },
    {
        prompt:'Who was Eamon Casey',
        optionA:'The first High King of Ireland',
        optionB:'An Irish Bishop',
        optionC:'Irelands first president',
        optionD:'The lover of Kitty OShea',
        url:'https://britishfoodhistory.files.wordpress.com/2020/07/20200626_174433-01.jpeg?w=1024',
        answer:'B', 
    },
    {
        prompt:'What caused the potatoe famine?',
        optionA:'The black death',
        optionB:'Foot and Mouth disease',
        optionC:'The potatoe blight',
        optionD:'Assuming Mr Potato heads gender',
        url:'https://d3nevzfk7ii3be.cloudfront.net/igi/JPpjbao64ZTJAPmV.large',
        answer:'C', 
    },
    {
        prompt:'What plant did St Patrick use?',
        optionA:'The Cannabis plant',
        optionB:'The four leaf clover',
        optionC:'The thistle',
        optionD:'The shamrock',
        url:'https://connachttribune.ie/wp-content/uploads/2019/03/St-Patricks-Day-image.jpg',
        answer:'D', 
    },
    {
        prompt:'Where was the High King Crowned',
        optionA:'Clifden',
        optionB:'Moath',
        optionC:'Tara',
        optionD:'Usually on his head',
        url:'https://irelandyes.files.wordpress.com/2011/12/kings-head-afc-web.jpg',
        answer:'C', 
    },
    {
        prompt:'When did Ireland become independent?',
        optionA:'1922',
        optionB:'1948',
        optionC:'1982',
        optionD:'1916',
        url:'https://img.rasset.ie/0013fc49-500.jpg',
        answer:'A', 
    },
    {
        prompt:'Who is the president of Ireland',
        optionA:'Mary Robinson',
        optionB:'Micheal Martin',
        optionC:'Douglas Hyde',
        optionD:'Michael D Higgins',
        url:'https://president.ie/images/made/fb667366461bb66f/Heber_McQuaid_2144_1424_c1_c_b_0_0_1.jpg',
        answer:'D', 
    },
    {
        prompt:'How many counties are in Ireland',
        optionA:'26',
        optionB:'32',
        optionC:'1916',
        optionD:'4',
        url:'https://www.tripsavvy.com/thmb/JvK9hXSeKisxptu0EHDJqJulOrI=/2123x1416/filters:fill(auto,1)/getty-sheep-ireland-56b61a465f9b5829f8309a0e.jpg',
        answer:'B', 
    },
    {
        prompt:'What is the northern most point in Ireland',
        optionA:'BlackHead',
        optionB:'Spanish Point',
        optionC:'Malin Head',
        optionD:'Mizen Head',
        url:'https://i.redd.it/1qt8ktfmkpg21.jpg',
        answer:'C', 
    },
]